const mongoose = require("mongoose");
const Schema = mongoose.Schema;

const Link = new Schema(
  {
    creator: {
      _id: false,
      userID: { type: Schema.Types.ObjectId },
    },

    link_code: { type: String, required: true, unique: true },

    redirect_data: [
      {
        referrer: { type: String },
        country: { type: String },
        OS: { type: String },
        date: { type: Date, default: Date.now() },
      },
    ],

    country: {
      Afghanistan: { type: Number },
      Albania: { type: Number },
      Algeria: { type: Number },
      Andorra: { type: Number },
      Angola: { type: Number },
      Antigua_Barbuda: { type: Number },
      Argentina: { type: Number },
      Armenia: { type: Number },
      Australia: { type: Number },
      Austria: { type: Number },
      Azerbaijan: { type: Number },
      The_Bahamas: { type: Number },
      Bahrain: { type: Number },
      Bangladesh: { type: Number },
      Barbados: { type: Number },
      Belarus: { type: Number },
      Belgium: { type: Number },
      Belize: { type: Number },
      Benin: { type: Number },
      Bhutan: { type: Number },
      Bolivia: { type: Number },
      Bosnia_Herzegovina: { type: Number },
      Botswana: { type: Number },
      Brazil: { type: Number },
      Brunei: { type: Number },
      Bulgaria: { type: Number },
      Burkina_Faso: { type: Number },
      Burundi: { type: Number },
      Cambodia: { type: Number },
      Cameroon: { type: Number },
      Canada: { type: Number },
      Cape_Verde: { type: Number },
      Chad: { type: Number },
      Chile: { type: Number },
      China: { type: Number },
      Colombia: { type: Number },
      Comoros: { type: Number },
      Costa_Rica: { type: Number },
      Ivory_Coast: { type: Number },
      Croatia: { type: Number },
      Cuba: { type: Number },
      Cyprus: { type: Number },
      Czech_Republic: { type: Number },
      Denmark: { type: Number },
      Djibouti: { type: Number },
      Dominica: { type: Number },
      Dominican_Republic: { type: Number },
      East_Timor: { type: Number },
      Ecuador: { type: Number },
      Egypt: { type: Number },
      El_Salvador: { type: Number },
      Equatorial_Guinea: { type: Number },
      Estonia: { type: Number },
      Ethiopia: { type: Number },
      Eritrea: { type: Number },
      Fiji: { type: Number },
      France: { type: Number },
      Finland: { type: Number },
      Gabon: { type: Number },
      The_Gambia: { type: Number },
      Georgia: { type: Number },
      Germany: { type: Number },
      Ghana: { type: Number },
      Greece: { type: Number },
      Grenada: { type: Number },
      Guatemala: { type: Number },
      Guinea: { type: Number },
      Guinea_Bissau: { type: Number },
      Guyana: { type: Number },
      Haiti: { type: Number },
      Honduras: { type: Number },
      Hungary: { type: Number },
      Iceland: { type: Number },
      India: { type: Number },
      Indonesia: { type: Number },
      Iran: { type: Number },
      Iraq: { type: Number },
      Ireland: { type: Number },
      Israel: { type: Number },
      Italy: { type: Number },
      Jamaica: { type: Number },
      Japan: { type: Number },
      Jordan: { type: Number },
      Kazakhstan: { type: Number },
      Kenya: { type: Number },
      Kiribati: { type: Number },
      Korea: { type: Number },
      Korea_North: { type: Number },
      Korea_South: { type: Number },
      Kuwait: { type: Number },
      Kyrgyzstan: { type: Number },
      Laos: { type: Number },
      Latvia: { type: Number },
      Lebanon: { type: Number },
      Libya: { type: Number },
      Liechtenstein: { type: Number },
      Lithuania: { type: Number },
      Luxembourg: { type: Number },
      Macedonia: { type: Number },
      Madagascar: { type: Number },
      Malawi: { type: Number },
      Malaysia: { type: Number },
      Maldives: { type: Number },
      Mali: { type: Number },
      Malta: { type: Number },
      Marshall_Islands: { type: Number },
      Mauritania: { type: Number },
      Mauritius: { type: Number },
      Mexico: { type: Number },
      Moldova: { type: Number },
      Mongolia: { type: Number },
      Montenegro: { type: Number },
      Morocco: { type: Number },
      Mozambique: { type: Number },
      Myanmar: { type: Number },
      Namibia: { type: Number },
      Nauru: { type: Number },
      Nepal: { type: Number },
      Netherlands: { type: Number },
      New_Zealand: { type: Number },
      Nicaragua: { type: Number },
      Niger: { type: Number },
      Nigeria: { type: Number },
      Norway: { type: Number },
      Oman: { type: Number },
      Pakistan: { type: Number },
      Palau: { type: Number },
      Panama: { type: Number },
      Papua_New_Guinea: { type: Number },
      Paraguay: { type: Number },
      Peru: { type: Number },
      Philippines: { type: Number },
      Poland: { type: Number },
      Portugal: { type: Number },
      Qatar: { type: Number },
      Romania: { type: Number },
      Russia: { type: Number },
      Rwanda: { type: Number },
      Saint_Lucia: { type: Number },
      Samoa: { type: Number },
      San_Marino: { type: Number },
      Saudi_Arabia: { type: Number },
      Senegal: { type: Number },
      Serbia: { type: Number },
      Seychelles: { type: Number },
      Sierra_Leone: { type: Number },
      Singapore: { type: Number },
      Slovakia: { type: Number },
      Slovenia: { type: Number },
      Solomon_Islands: { type: Number },
      Somalia: { type: Number },
      South_Africa: { type: Number },
      Spain: { type: Number },
      Sri_Lanka: { type: Number },
      Sudan: { type: Number },
      Suriname: { type: Number },
      Swaziland: { type: Number },
      Sweden: { type: Number },
      Switzerland: { type: Number },
      Syria: { type: Number },
      Tajikistan: { type: Number },
      Tanzania: { type: Number },
      Thailand: { type: Number },
      Togo: { type: Number },
      Tonga: { type: Number },
      Tunisia: { type: Number },
      Turkey: { type: Number },
      Turkmenistan: { type: Number },
      Tuvalu: { type: Number },
      Uganda: { type: Number },
      Ukraine: { type: Number },
      United_Arab_Emirates: { type: Number },
      United_Kingdom: { type: Number },
      United_States: { type: Number },
      Uruguay: { type: Number },
      Uzbekistan: { type: Number },
      Vanuatu: { type: Number },
      Vatican_City: { type: Number },
      Venezuela: { type: Number },
      Vietnam: { type: Number },
      Yemen: { type: Number },
      Zambia: { type: Number },
      Zimbabwe: { type: Number },
    },
  },
  { timestamps: true }
);

module.exports = mongoose.model("link", Link);
